\input texinfo
@setfilename manual
@settitle 3DViewer_v1.0
@documentencoding UTF-8

@copying
Copyright © 2023 by winfordt-armorcoo-parasits
@end copying

@titlepage
@title Небольшая инструкция по использованию 3DViewer
@vskip
@insertcopying
@author Нияз Хазигалеев, Дастан Османалиев, Ирина Макарова
@end titlepage

@ifnottex
@node Top
@top 3DViewer_v1.0
@insertcopying
@end ifnottex

@menu
* General information:: В этом разделе представлена общая информация о принципе работы 3DViewer.
* Affine transformations:: В этом разделе представлена информация о реализации Аффиных преорбразований.
* Obj file:: В этом разделе представлена информация о списке реализованных математических функций.
* info:: В этом разделе представлена информация о возможности построения графиков функций.
* Part_1:: В этом разделе представлена информация о возможности использования кредитного калькулятора.
* Part_2:: В этом разделе представлена информация о возможности использования депозитного калькулятора.
@end menu

@node General information
@chapter General information

Разработана программа для визуализации каркасных моделей в трехмерном пространстве на языке программирования C/C++ с использованием QT Creator версии 5.12.@*

@node  Affine transformations
@chapter  Affine transformations

Аффинное преобразование - отображение плоскости или пространства в себя, при котором параллельные прямые переходят в параллельные прямые, пересекающиеся — в пересекающиеся, скрещивающиеся — в скрещивающиеся.@*
Преобразование плоскости называется аффинным если оно взаимно однозначно и образом любой прямой является прямая. Преобразование (отображение) называется взаимно однозначным (биективным), если оно переводит разные точки в разные, и в каждую точку переходит какая-то точка.@*
С алгебраической точки зрения аффинное преобразование это преобразование вида: f(x) = M * x + v, где M - некая обратимая матрица, а v - какое-то значение.@*

Свойства аффинных преобразований:
@enumerate
@item
Композиция аффинных преобразований есть снова аффинное преобразование.
@item
Преобразование, обратное к аффинному, есть снова аффинное преобразование.
@item
Отношение площадей сохраняется.
@item
Отношение длин отрезков на прямой сохраняется.
@end enumerate

Перемещение@*
где a и b - величины по x и y, на которые необходимо переместить исходную точку. Таким образом, чтобы переместить точку необходимо умножить матрицу перемещения на нее:
где x и y - исходные координаты точки, а x1 и y1 - полученные координаты новой точки после перемещения.@*

Поворот@*
Матрица поворота по часовой стрелке в однородных двумерных координатах:
где a - угол поворота в двумерном пространстве. Для получения координат новой точки необходимо также, как и матрицу перемещения, перемножить матрицу поворота на исходную точку:@*

Масштабирование@*
Матрица масштабирования в однородных двумерных координатах:
где a и b - коэффициенты масштабирования соответственно по осям OX и OY. Получение координат новой точки происходит аналогично описанным выше случаям
@node Obj file
@chapter Obj file

Файлы .obj - это формат файла описания геометрии, впервые разработанный компанией Wavefront Technologies. Формат файла открыт и принят многими поставщиками приложений для 3D-графики.@*

Формат файла .obj - это простой формат данных, который представляет только трехмерную геометрию, а именно положение каждой вершины, положение UV координат текстуры каждой вершины, нормали вершин и грани, которые определяют каждый многоугольник как список вершин и вершин текстуры. Координаты obj не имеют единиц измерения, но файлы obj могут содержать информацию о масштабе в удобочитаемой строке комментариев.

@node info
@chapter info

При написании кода придерживались Google Style@*
Обеспечено покрытие unit-тестами модулей, связанных с загрузкой моделей и аффинными преобразованиями.@*
Программа предоставляет возможность.@*
- Загружать каркасную модель из файла формата obj (поддержка только списка вершин и поверхностей).@*
- Перемещать модель на заданное расстояние относительно осей X, Y, Z..@*
- Поворачивать модель на заданный угол относительно своих осей X, Y, Z@*
- Масштабировать модель на заданное значение.@*
- Выводить информацию о загруженной модели - название файла, кол-во вершин и ребер


@node Part_1
@chapter Part_1
В этой части реализованы базовые настройки и просмотра модели@*
- Программа позволяет настраивать тип проекции (параллельная и центральная)@*
- Программа позволяет настраивать тип (сплошная, пунктирная), цвет и толщину ребер, способ отображения (отсутствует, круг, квадрат), цвет и размер вершин@*
- Программа позволяет выбирать цвет фона@*
- Настройки сохраняются между перезапусками программы@*
@node Part_2
@chapter Part_2
Программа имеет специальный режим записи изображения и gif-анимации и сохраняются в произвольный каталог@*
- Программа позволяет сохранять полученные ("отрендеренные") изображения в файл во множествах форматах@*
- Программа позволяеи по специальной кнопке записывать небольшие "скринкасты" - текущие пользовательские аффинные преобразования загруженного объекта в gif-анимацию (640x480, 10fps, 5s)@*

@bye
